# Generated by Django 3.2.15 on 2022-09-20 16:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_about_cover_photo_portfolio_resume_services_skills_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfolio',
            options={'verbose_name_plural': 'Portfolio'},
        ),
        migrations.AlterModelOptions(
            name='testimonials',
            options={'verbose_name_plural': 'Testimonials'},
        ),
        migrations.AlterField(
            model_name='contact_us_form',
            name='Time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 9, 20, 19, 59, 5, 878376)),
        ),
    ]
